name: push tests
run-name: ${{ github.actor }} triggered test run
on: [push]
jobs:
  run-all-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: mkdir artifacts
      - run: npm install -g typescript
      - run: npm install --save-dev cypress
      - run: npm install --save-dev @types/mocha
      - run: npm install --save-dev mochawesome
      - run: npm install --save-dev moment
      - run: npx tsc
      - run: npx cypress run 
      - uses: actions/upload-artifact@v3
        with:
          name: reports-folder
          path: artifacts/